### ISSUE TITLE
Improvements to the readme.md

### ISSUE THREAD

**Issue by jeherve** [Automattic/wordpress-activitypub#439]
Right now, the repo's `readme.md` is a copy of the plugin's `readme.txt`, and we rely on the `wp-readme-to-markdown` grunt plugin to keep the 2 files in sync.

While that makes sense, I'd like to offer some improvements:

```[tasklist]
### Tasks
- [ ] Extract changelog
- [ ] Add Security section
- [ ] Add Join us section
- [ ] Add Contributing / How to build section
```

See Details below.

**********

- The changelog is getting long, and I don't know if it is very useful for folks landing in this repo to see the full changelog. Maybe we could link to a `changelog.md` file instead, or to the `readme.txt`'s changelog section?
- I think it would be nice to add 3 new sections to the readme.md file:

1) a "Security" section that would help folks know what to do if they want to report a security issue. Something like this:

```md
## Security

Need to report a security vulnerability? Go to [https://automattic.com/security/](https://automattic.com/security/) or directly to our security bug bounty site [https://hackerone.com/automattic](https://hackerone.com/automattic).
```

2) A "Join us" section to invite folks interested in Automattic. Something like this:

```md
## Join us!

Interested in working on awesome open-source code all day? [Join us](https://automattic.com/work-with-us/)!
```

3) Since we're on GitHub where the plugin needs to be built, maybe there should be a section mentioning the necessary tools to work in this repo, and what to do to build the plugin?

**********

@pfefferle What do you think?

**Comment by pfefferle** [comment]
@jeherve would you like to work on that?

**Comment by jeherve** [comment]
I'm not super familiar with your Grunt config, but I can take a look for sure, at some point in the next few weeks.

**Comment by pfefferle** [comment]
We do not have to stick with grunt!
